### ISSUE TITLE
HBA / HBD selection fragile, should use elements

### ISSUE THREAD

**Issue by hmacdope** [asapdiscovery/choppa#8]
```python
            # we only want to show HBD/HBA
            if contacted_lig_at.type == "N" and contacted_res_at.type == "O" or \
                            contacted_lig_at.type == "O" and contacted_res_at.type == "N":
                contacts.append([contacted_lig_at, contacted_res_at])
```
In util is a bit fragile as it depends on atom `types`, instead should query atom elements, as types can be anything.

**Comment by JenkeScheen** [comment]
can you point me to the atom element method in MDA?

**Comment by hmacdope** [comment]
should just be the `contacted_lig.element` https://userguide.mdanalysis.org/stable/topology_system.html

**Comment by JenkeScheen** [comment]
fixed in https://github.com/asapdiscovery/choppa/pull/16/commits/d7eada4d6729bb86750b7a71fc327c1b539105b2
